services:
  - type: web
    name: mypocketlawyer
    env: docker
    plan: free
    branch: main
    repo: https://github.com/horkydorky/lawyer
    numInstances: 1
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
